Add output dir to dotnet-compile-native, fix manpage manifest generation

diff --git a/iltonative_package/builtins/dotnet-compile-native b/iltonative_package/builtins/dotnet-compile-native
--- a/iltonative_package/builtins/dotnet-compile-native
+++ b/iltonative_package/builtins/dotnet-compile-native
@@ -12,19 +12,12 @@ c_flags="-g -lstdc++ -lrt -Wno-invalid-offsetof"
 
 il_to_cpp_args="-r ${INSTALL_ROOT}/native/lib/Unix/*.dll -r ${INSTALL_ROOT}/native/lib/*.dll -llvm"
 
-output_directory=$(pwd)
-
 print_usage(){
-		echo "Usage: dotnet-native-compile [il_assembly_path] [output_dir]"
+	echo "Usage: dotnet-native-compile [il_assembly_path] [output_dir]"
 }
 
+# Usage: il_to_cpp [il assembly file]
 il_to_cpp(){
-	if [ -z "$1" ] || [ ! -f "$1" ]; then
-		echo "Error: Invalid il assembly path"
-		echo "$1"
-		exit 1
-	fi
-
 	il_assembly_file="$1"
 	il_assembly_filename=$(basename "$il_assembly_file" .dll)
 
@@ -37,16 +30,13 @@ il_to_cpp(){
 	echo $intermediate_cpp_file
 }
 
+# Usage: cpp_to_native [cpp file] [output dir]
 cpp_to_native(){
-	if [ -z "$1" ] || [ ! -f "$1" ]; then
-		echo "Error: Invalid cpp file"
-		echo "$1"
-		exit 1
-	fi
-
-	cpp_file="/tmp/hello.cpp"
+	
+	cpp_file="$1"
 	cpp_filename=$(basename "$cpp_file" .cpp)
 
+	output_directory="$2"
 	output_file=$output_directory/${cpp_filename}
 	rm -f $output_file
 
@@ -54,19 +44,32 @@ cpp_to_native(){
 	full_command="clang-3.5 $c_flags $c_includes $cpp_file $c_libs -o $output_file"
 
 	$full_command > /dev/null
-	chmod u+rwx $output_file
+	chmod u+x $output_file
 
 	echo $output_file
 }
 
-if [ -z "$1" ] || [ ! -f "$1" ]; then
-	print_usage
-	exit 1
-fi
+validate_args(){
+	if [ -z "$1" ] || [ ! -f "$1" ]; then
+		echo "Error: Invalid il_assembly_path argument"
+		print_usage
+		exit 1
+	fi
+
+	if [ -z "$2" ] || [ ! -d "$2" ]; then
+		echo "Error: Invalid output_dir argument"
+		print_usage
+		exit 1
+	fi
+}
+
+validate_args $@
 
 echo "Converting $1 to native"
 
 tmp_cpp_file="$(il_to_cpp "$1")"
-output_executable="$(cpp_to_native "$tmp_cpp_file")"
+output_executable="$(cpp_to_native "$tmp_cpp_file" "$2")"
 
-echo "Native Output: $output_executable"
+echo "native output: $output_executable"
+
+exit 0
